version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: myskinmetrix_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myskinmetrix
      POSTGRES_PASSWORD: myskinmetrix
      POSTGRES_DB: myskinmetrix
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 